CREATE TABLE IF NOT EXISTS orders
(
    order_uid VARCHAR(256) NOT NULL DEFAULT "",
    track_number VARCHAR(256) NOT NULL DEFAULT "",
    entry VARCHAR(256) NOT NULL DEFAULT "",
    delivery VARCHAR(256) NOT NULL DEFAULT "",
    locale VARCHAR(256) NOT NULL DEFAULT "",
    internal_signature VARCHAR(256) NOT NULL DEFAULT "",
	customer_id VARCHAR(256) NOT NULL DEFAULT "",       
	delivery_service VARCHAR(256) NOT NULL DEFAULT "",  
	shardkey VARCHAR(256) NOT NULL DEFAULT "",          
	sm_id VARCHAR(256) NOT NULL DEFAULT "",          
	date_created VARCHAR(256) NOT NULL DEFAULT "",     
	oof_shard VARCHAR(256) NOT NULL DEFAULT "",       
	items VARCHAR(256) NOT NULL DEFAULT "",         
	payment VARCHAR(256) NOT NULL DEFAULT ""
);

CREATE TABLE IF NOT EXISTS deliveries
(
	delivery_id INT PRIMARY KEY NOT NULL,
	name VARCHAR(256) NOT NULL DEFAULT "",       
	phone VARCHAR(256) NOT NULL DEFAULT "",      
	zip VARCHAR(256) NOT NULL DEFAULT "",        
	city VARCHAR(256) NOT NULL DEFAULT "",       
	address VARCHAR(256) NOT NULL DEFAULT "",     
	region VARCHAR(256) NOT NULL DEFAULT "",      
	email VARCHAR(256) NOT NULL DEFAULT ""      
);

CREATE TABLE IF NOT EXISTS payments
(
	transaction VARCHAR(256) NOT NULL DEFAULT "",  
	request_id VARCHAR(256) NOT NULL DEFAULT "",  
	currency VARCHAR(256) NOT NULL DEFAULT "",  
	provider VARCHAR(256) NOT NULL DEFAULT "",  
	amount VARCHAR(256) NOT NULL DEFAULT "",  
	payment_dt INTEGER NOT NULL DEFAULT 0,
	bank VARCHAR(256) NOT NULL DEFAULT "",
	delivery_cost INTEGER NOT NULL DEFAULT 0,
	goods_total INTEGER NOT NULL DEFAULT 0,
	custom_fee INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS items
(
	chrt_id INT PRIMARY KEY NOT NULL,
	track_number VARCHAR(256) NOT NULL DEFAULT "",
	price INTEGER NOT NULL DEFAULT 0,
	rid VARCHAR(256) NOT NULL DEFAULT "",
	name VARCHAR(256) NOT NULL DEFAULT "",
	sale INTEGER NOT NULL DEFAULT 0,
	size VARCHAR(256) NOT NULL DEFAULT "",
	total_price INTEGER NOT NULL DEFAULT 0,
	nm_id INTEGER NOT NULL DEFAULT 0,
	brand VARCHAR(256) NOT NULL DEFAULT "",
	status INTEGER NOT NULL DEFAULT 0
);