services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    command: go run cmd/main.go
    depends_on:
      - db
  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5436:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U postgres -d demonstrate_orders_test"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: